# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
      - name: CI
        working-directory: ./
        run: |
          sudo mkdir -p /vis/km
          sudo chown -R runner:docker /vis/km
          sudo chmod -R 777 /vis/km
          mvn clean install
        env:
          CI: false
